### ISSUE TITLE
Parsing callbacks flattens arrays

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#20]
Using this `altapay.utils.etree_to_dict()` function to parse XML for `callback_ok`flattens the **transactions** array, if there's just one **transaction**. 

The correct behaviour would be to have **transactions** be an array, always, regardless of the number of transactions returned. 
`transactions: [ transaction, ]`

**Comment by HenrikOssipoff** [comment]
Fixed in 0.1.dev2
