### ISSUE TITLE
Ease implementation by wrapping AltaPay callback XML

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#21]
Rather than dealing with generic `transactions`, the API should provide a `Callback` class. The `Callback` would do an initial parsing of the callback XML data, and allow for features like filtering on transaction types. 

E.g. when dealing with **subscriptionAndReserve** it would in some case be beneficial to be able to process the **subscription_payment** transactions before the **subscriptionAndReserve** transactions. This is the case if you wish to use subscriptions as a backup option when handling pre-orders where the initial reserve might expire before a `capture` can be made.

**Comment by HenrikOssipoff** [comment]
Fixed in 0.1.dev2
