### ISSUE TITLE
Transaction callback XML is parsed wrong

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#22]
Then a callback includes multiple `transaction` elements, the resulting dictionary is weirdly formed.

The *transactions* key will not return an array of `transaction` elements, but rather a new dictionary, with just one key, called *transaction*. The value of the *transaction* entry is an array of `transaction` elements. 

A prettier solution is to discard the *transaction* key and move the `transaction` element array to the *transactions* key.

**Comment by HenrikOssipoff** [comment]
Fixed in 0.1.dev2
