### ISSUE TITLE
Callback doesn't handle callback XML with one transaction

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#25]
If the XML in a callback only contains one transaction the `transactions(auth_type='subscription_payment')`will result in a KeyError.

`File "/opt/projects/virtualenv/coolpay2/lib/python3.5/site-packages/altapay/callback.py", line 29, in <listcomp>
    if transaction['AuthType'] == auth_type
KeyError: 'AuthType'`

**Comment by HenrikOssipoff** [comment]
Will be fixed in 0.1.dev3.
