### ISSUE TITLE
Transaction.charge_subscription throws again response data.

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#36]
The charge_subscription method on a Transaction object will return a list of transactions, and discard relevant error message in case of failure. 

The response should be converted to a Callback object instead. 

Callback.transactions(auth_type=<XYZ>) also won't work, because the returned transactions does not have an auth_type. Filter could/should be extended to allow filtering on the "TransactionStatus" field.

**Comment by HenrikOssipoff** [comment]
Will be fixed in 1.0.dev5
